### ISSUE TITLE
uploads are disabled

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/OGC-ISG-Sprint-Sep-2020#3]
Hi Scott,

I can't upload the slides to the repo: uploads are disabled. 

[STT ISG Sprint Participant Kickoff.pptx](https://github.com/opengeospatial/OGC-ISG-Sprint-Sep-2020/files/5151671/STT.ISG.Sprint.Participant.Kickoff.pptx)

**Comment by volkercoors** [comment]
@serich and I can't assign this issue to you.

**Comment by ogcscotts** [comment]
@volkercoors you will need to opt-in to the repo on the initiative home page on the OGC Portal here: https://portal.ogc.org/?m=projects&a=view&project_id=623&tab=0

**Comment by volkercoors** [comment]
I am confused. On the portal, it looks like we use gitlab (great!!!), but this is github. And it looks like there is no project on gitlab. I better wait for tomorrows instructions.

**Comment by serich** [comment]
@volkercoors I went ahead and uploaded your slide deck and sent you a separate email with a screenshot showing where to click the GitHub repo link (not to be confused with the GitLab repo link). I also put out an inquiry in the new Slack workspace. We'll get things sorted out soon... sorry for the trouble!

**Comment by serich** [comment]
@volkercoors I *think* I just granted you Write access, so give it a try when you get a chance and let me know how it goes... maybe try assigning this issue to me again.

**Comment by volkercoors** [comment]
perfect, successfully uploaded a file. First issue solved already, even before the kickoff. Great.
