### ISSUE TITLE
mapping table github id and Name / Organisation

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/OGC-ISG-Sprint-Sep-2020#7]
gitlab id, Name / Organization, slack id, maybe a picture as well. So we know who is who.

**Comment by serich** [comment]
Here's the initial [wiki page](https://github.com/opengeospatial/OGC-ISG-Sprint-Sep-2020/wiki/GitHub-and-Slack-IDs).

I believe anybody can edit it to add info. Otherwise let me know and I can add it.
